fixed regex dependency conflict
ERROR: Cannot install -r requirements.txt (line 19) and regex==2020.11.13 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested regex==2020.11.13
    nltk 3.6.5 depends on regex>=2021.8.3